wsdl2java/java2wsdl scripts fixed up to work for src & bin distros.
Fixes to .bat files to follow, once I get set up on Windows.


git-svn-id: https://svn.apache.org/repos/asf/incubator/cxf/trunk@435089 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/bin/wsdl2java b/bin/wsdl2java
--- a/bin/wsdl2java
+++ b/bin/wsdl2java
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/ksh
 # run the Celtix wsdl2java tool 
 #
 
@@ -8,8 +8,11 @@ celtix_home=`dirname $0`/..
 celtix_jar=$celtix_home/lib/celtix.jar
 
 if [ ! -e $celtix_jar ]; then 
-    echo "unable to find celtix.jar in $celtix_home/lib"
-    exit 1
+    celtix_jar=$celtix_home/build/lib/celtix.jar
+    if [ ! -e $celtix_jar ]; then 
+        echo "unable to find celtix.jar in $celtix_home/lib"
+        exit 1
+    fi
 fi 
 
 #
@@ -22,8 +25,11 @@ fi
 jaxws_home=$celtix_home/lib/jaxws-ri/20051104/
 
 if [ ! -e $jaxws_home ]; then 
-    echo "unable to find JAXWS RI"
-    exit 1
+    jaxws_home=$celtix_home/tools/jaxws-ri/20051104/
+    if [ ! -e $jaxws_home ]; then 
+        echo "unable to find JAXWS RI"
+        exit 1
+    fi 
 fi 
 
 log_config=$celtix_home/etc/logging.properties 
