remove celtix_env update tool scripts to figure out the environment for themselves
git-svn-id: https://svn.apache.org/repos/asf/incubator/cxf/trunk@434879 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/bin/wsdl2java b/bin/wsdl2java
--- a/bin/wsdl2java
+++ b/bin/wsdl2java
@@ -2,14 +2,32 @@
 # run the Celtix wsdl2java tool 
 #
 
-if [ ${CELTIX_HOME-"x"} == "x" ]; then
-    echo "The CELTIX_HOME environment variable is unset.  Please set CELTIX_HOME"
-    echo "envionment variable to the location of the Celtix installation"
-    return 1
+me=`basename $0`
+celtix_home=`dirname $0`/..
+
+celtix_jar=$celtix_home/lib/celtix.jar
+
+if [ ! -e $celtix_jar ]; then 
+    echo "unable to find celtix.jar in $celtix_home/lib"
+    exit 1
+fi 
+
+#
+# add the jdk's tools.jar to the classpath
+#
+if [ -e "${JAVA_HOME}/lib/tools.jar" ]; then
+    CLASSPATH=${JAVA_HOME}/lib/tools.jar:$CLASSPATH
 fi
 
-source $CELTIX_HOME/bin/celtix_env
+jaxws_home=$celtix_home/lib/jaxws-ri/20051104/
 
-$JAVA_HOME/bin/java -Djaxws.home=$JAXWS_HOME -Djava.util.logging.config.file=$CELTIX_HOME/etc/logging.properties org.objectweb.celtix.tools.Wsdl2Java "$@"
+if [ ! -e $jaxws_home ]; then 
+    echo "unable to find JAXWS RI"
+    exit 1
+fi 
+
+log_config=$celtix_home/etc/logging.properties 
+
+$JAVA_HOME/bin/java -cp $celtix_jar -Djaxws.home=$jaxws_home -Djava.util.logging.config.file=$log_config org.objectweb.celtix.tools.Wsdl2Java "$@"
 
 
