[CXF-809] Applied Benson's improved version java2wsdl script to support cygwin, also updated other wsdl2* script.
git-svn-id: https://svn.apache.org/repos/asf/incubator/cxf/trunk@558961 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/distribution/src/main/release/bin/xsd2wsdl b/distribution/src/main/release/bin/xsd2wsdl
--- a/distribution/src/main/release/bin/xsd2wsdl
+++ b/distribution/src/main/release/bin/xsd2wsdl
@@ -21,6 +21,17 @@
 #!/bin/sh
 # run the Apache CXF xsd2wsdl tool 
 #
+# Check for irritating 'operating systems'.
+cygwin=false;
+darwin=false;
+case "`uname`" in
+  CYGWIN*) cygwin=true ;;
+  Darwin*) darwin=true
+           if [ -z "$JAVA_HOME" ] ; then
+             JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Home
+           fi
+           ;;
+esac
 
 me=`basename $0`
 cxf_home=$CXF_HOME
@@ -44,17 +55,34 @@ fi
 # add the jdk's tools.jar to the classpath
 #
 
-sun_tool_path=${JAVA_HOME}/lib/tools.jar
+sun_tool_path=""
+if [ $darwin == false ]; then
+    sun_tool_path=${JAVA_HOME}/lib/tools.jar
+    if [ ! -f $sun_tool_path ]; then
+	echo "ERROR: Set JAVA_HOME to the path where the J2SE 5.0 (JDK5.0) is installed"
+	exit 1
+    fi
+fi 
 
-if [ ! -f $sun_tool_path ]; then
-    echo "ERROR: Set JAVA_HOME to the path where the J2SE 5.0 (JDK5.0) is installed"
-    exit 1
-fi
 
 log_config=$cxf_home/etc/logging.properties 
-
-cxf_classpath=${cxf_jar}:${CLASSPATH}:${sun_tool_path}
-
+if $cygwin; then
+  if [ "$OS" = "Windows_NT" ] && cygpath -m .>/dev/null 2>/dev/null ; then
+    format=mixed
+  else
+    format=windows
+  fi
+  cxf_classpath=`cygpath --$format "${cxf_jar}"`
+  if [ ! -z "${CLASSPATH}" ]; then
+    cxf_classpath=${cxf_classpath}\;`cygpath --$format --path "${CLASSPATH}"`
+  fi
+  if [ ! -z "${sun_tool_path}" ] ; then
+    cxf_classpath=${cxf_classpath}\;`cygpath --$format "${sun_tool_path}"`
+  fi
+  log_config=`cygpath --$format "$log_config"`
+else
+   cxf_classpath=${cxf_jar}:${CLASSPATH}:${sun_tool_path}
+fi
 $JAVA_HOME/bin/java -cp ${cxf_classpath} -Djava.util.logging.config.file=$log_config org.apache.cxf.tools.misc.XSDToWSDL "$@"
 
 
