Modified script classpath
git-svn-id: https://svn.apache.org/repos/asf/incubator/cxf/trunk@435592 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/celtix-distribution/src/main/bin/java2wsdl b/celtix-distribution/src/main/bin/java2wsdl
--- a/celtix-distribution/src/main/bin/java2wsdl
+++ b/celtix-distribution/src/main/bin/java2wsdl
@@ -7,23 +7,18 @@ celtix_home=`dirname $0`/..
 
 celtix_jar=$celtix_home/lib/celtix.jar
 
-if [ ! -f $celtix_jar ]; then 
-    if [ ! -f $celtix_home/../../target/srcbuild_env ]; then 
-        echo "unable to find celtix.jar in $celtix_home/lib"
-        exit 1
-    else
-        . $celtix_home/../../target/srcbuild_env
-        celtix_jar=${CELTIX_CLASSPATH}
-    fi
+if [ ! -f $celtix_jar ]; then  
+    echo "unable to find celtix.jar in $celtix_home/lib"
+    exit 1
 fi 
 
 #
 # add the jdk's tools.jar to the classpath
 #
 if [ -f "${JAVA_HOME}/lib/tools.jar" ]; then
-    CLASSPATH=${JAVA_HOME}/lib/tools.jar:$CLASSPATH
+    tool_path=${JAVA_HOME}/lib/tools.jar
 fi
 log_config=$celtix_home/etc/logging.properties 
 
-
-$JAVA_HOME/bin/java -cp $celtix_jar -Djava.util.logging.config.file=$log_config org.objectweb.celtix.tools.JavaToWSDL "$@"
+celtix_classpath=${celtix_jar}:${CLASSPATH}:${tool_path}
+$JAVA_HOME/bin/java -cp ${celtix_classpath} -Djava.util.logging.config.file=$log_config org.objectweb.celtix.tools.JavaToWSDL "$@"
