Removed repeat content appended to classpath when run the script for many times
Added wsdl2xml script

git-svn-id: https://svn.apache.org/repos/asf/incubator/cxf/trunk@435595 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/celtix-distribution/src/main/bin/wsdl2soap b/celtix-distribution/src/main/bin/wsdl2soap
--- a/celtix-distribution/src/main/bin/wsdl2soap
+++ b/celtix-distribution/src/main/bin/wsdl2soap
@@ -8,23 +8,28 @@ celtix_home=`dirname $0`/..
 celtix_jar=$celtix_home/lib/celtix.jar
 
 if [ ! -f $celtix_jar ]; then 
-    if [ ! -f $celtix_home/../../target/srcbuild_env ]; then 
-        echo "unable to find celtix.jar in $celtix_home/lib"
-        exit 1
-    else
-        . $celtix_home/../../target/srcbuild_env
-        celtix_jar=${CELTIX_CLASSPATH}
-    fi
+    echo "unable to find celtix.jar in $celtix_home/lib"
+    exit 1
 fi 
 
 #
 # add the jdk's tools.jar to the classpath
 #
-if [ -f "${JAVA_HOME}/lib/tools.jar" ]; then
-    CLASSPATH=${JAVA_HOME}/lib/tools.jar:$CLASSPATH
+
+sun_tool_path=${JAVA_HOME}/lib/tools.jar
+
+if [ ! -f $sun_tool_path ]; then
+    echo "Please set JAVA_HOME to point a J2SE 5.0 Development Kit"
+    exit 1
 fi
 
 log_config=$celtix_home/etc/logging.properties 
 
+celtix_classpath=${celtix_jar}:${CLASSPATH}:${sun_tool_path}
 
-$JAVA_HOME/bin/java -cp $celtix_jar -Djaxws.home=$celtix_home -Djava.util.logging.config.file=$log_config org.objectweb.celtix.tools.WSDLToSoap "$@"
+$JAVA_HOME/bin/java -cp ${celtix_classpath} -Djaxws.home=$celtix_home -Djava.util.logging.config.file=$log_config org.objectweb.celtix.tools.WSDLToSoap "$@"
+
+
+
+
+
