Update eclipse setup, fix shell scripts
* Update eclipse setup to run the install at the sametime as the eclipse:eclipse.  This allows the axis project to work correctly.
* Fix all the shell scripts to work in a source distribution.




git-svn-id: https://svn.apache.org/repos/asf/incubator/cxf/trunk@435825 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/celtix-distribution/src/main/bin/wsdl2xml b/celtix-distribution/src/main/bin/wsdl2xml
--- a/celtix-distribution/src/main/bin/wsdl2xml
+++ b/celtix-distribution/src/main/bin/wsdl2xml
@@ -8,9 +8,14 @@ celtix_home=`dirname $0`/..
 celtix_jar=$celtix_home/lib/celtix.jar
 
 if [ ! -f $celtix_jar ]; then 
-    echo "ERROR: Unable to find celtix.jar in $celtix_home/lib"
-    exit 1
-fi 
+    if [ ! -f ${celtix_home}/../../target/srcbuild_env ]; then
+        echo "ERROR: Unable to find celtix.jar in $celtix_home/lib"
+        exit 1
+    else
+        . ${celtix_home}/../../target/srcbuild_env
+        celtix_jar=${CELTIX_CLASSPATH}
+    fi
+fi  
 
 #
 # add the jdk's tools.jar to the classpath
